# Detection receiver config
SERVER:
    DIR: "server/"
    TIMEOUT: 10.0
    CLEAR: True

# Controller config
CONTROLLER:
    # IP: [127.0.0.1]
    IP: ["192.168.50.119"]
    PORT: ["4000"]

# Edge device config
EDGE:
    DIR: "edge/"
    NB: 100
    STEP: 1
    CLEAR: True

# List of publishers IPs
PUBLISHERS:
    IP: ["192.168.50.127", "192.168.50.135", "192.168.50.143", "192.168.50.151"]
    PORT_IMG: ["5550"]
    PORT_PTS: ["5555"]

# Camera config
CAMERA:
    FPS: 60
    EXPOSURE: 6000
    EXT_TRIGGER: True

# Detection config
DETECTION:
    MODE: 0
    BY_MARKERS:
        BIN_THR: 180 # 180
        K_SIZE: 21 # 21
        CIRC_THR: 0.2 # 0.8
        W_H_DIFF: 20 # 20
        MARK_SIZE: 50 # 100
        AREA_THR: 1 # 80
    BY_FOREGROUND:
        THR: 0

# Stereo calibration config
CALIB:
    ROWS: 6
    COLS: 9
