# Main server general configuration
SERVER:
    DIR: "received_data/"
    TIMEOUT: 10.0
    CLEAR: True

# Controller general configuration
CONTROLLER:
    IP: [127.0.0.1] # ["192.168.50.119"]
    PORT: ["4000"]

# Edge device general configuration
EDGE:
    DIR: "recorded_data/"
    NB: 100
    STEP: 1
    CLEAR: True

# List of publishers IP addresses
PUBLISHERS:
    IP: ["192.168.50.127", "192.168.50.135", "192.168.50.143", "192.168.50.151"]
    PORT: ["5555", "5550"]

# Camera general configuration
CAMERA:
    FPS: 60
    EXPOSURE: 6000
    EXT_TRIGGER: False
    IM_HEIGHT: 1.0
    IM_WIDTH: 1.0

# Markers detectin parameters
DETECTION:
    BIN_THR: 160 # 180
    K_SIZE: 21 # 21
    CIRC_THR: 0.2 # 0.8
    W_H_DIFF: 20 # 20
    MARK_SIZE: 20 # 100
    AREA_THR: 1 # 80

# Stereo calibration parameteres
CALIB:
    ROWS: 6
    COLS: 9
